// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lvcumttjgssfcejhvigi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imx2Y3VtdHRqZ3NzZmNlamh2aWdpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzM5NDkyNzksImV4cCI6MjA0OTUyNTI3OX0.VQinOIjKyd2RZliZROZBmCV8BU-lKDEp1AHOl5QR9Co";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);